apiVersion: transformers.giantswarm.io/v1
kind: Konfigure
metadata:
  name: konfigure-plugin
  annotations:
    config.kubernetes.io/function: |
      container:
        image: docker.io/wttyf00l/konfigure-plugin:latest
data:
  registry: docker.io
  ttl: 24h

